retargeting:
  type: vector
  urdf_path: barrett_hand/bhand_model.urdf

  # Target refers to the retargeting target, which is the robot hand
  #target_joint_names: [ 'finger_1_dist_joint', 'finger_2_dist_joint', 'finger_3_dist_joint']
  target_origin_link_names: [ "base_link", "base_link", "base_link"]
  target_task_link_names: [ "finger_1_dist_link",  "finger_2_dist_link", "finger_3_dist_link"]
  scaling_factor: 1.0

  # Source refers to the retargeting input, which usually corresponds to the human hand
  # The joint indices of human hand joint which corresponds to each link in the target_link_names
  target_link_human_indices: [ [ 0, 0, 0], [ 4, 8, 12] ]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2